on:
  release:
    types: [created]

jobs:
  releases-matrix:
    name: release linux/amd64
    runs-on: ubuntu-latest
    strategy:
      matrix:
        goarch: [arm, amd64, arm64]
    steps:
      - uses: actions/checkout@v3
      - uses: wangyoucao577/go-release-action@v1.32
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          goos: linux
          goarch: ${{ matrix.goarch }}
          md5sum: false
          asset_name: lego-directadmin-${{ matrix.goarch }}
          goversion: 1.18
